# DROP TABLE OSS_STORE;
# DROP TABLE OSS_DATA;

CREATE TABLE OSS_STORE
(
    ID               VARCHAR(50) PRIMARY KEY COMMENT '主键',
    NAME             VARCHAR(100) NOT NULL COMMENT '文件/目录名',
    PATH             VARCHAR(500) NOT NULL COMMENT '路径',
    LENGTH           LONG COMMENT '文件大小',
    CREATE_TIME      DATETIME COMMENT '创建时间',
    LAST_UPDATE_TIME DATETIME COMMENT '最新修改时间',
    PARENT_ID        VARCHAR(50) DEFAULT 0 COMMENT '父级目录ID',
    TYPE             VARCHAR(2)   NOT NULL COMMENT '类型(D:目录;F:文件)',
    DATA_ID          VARCHAR(50) COMMENT '数据ID'
) COMMENT '对象存储';

CREATE INDEX OSS_STORE_NAME_INDEX ON OSS_STORE (NAME);
CREATE INDEX OSS_STORE_PATH_INDEX ON OSS_STORE (PATH);
CREATE INDEX OSS_STORE_PARENT_INDEX ON OSS_STORE (PARENT_ID);

CREATE TABLE OSS_DATA
(
    ID   VARCHAR(50) PRIMARY KEY COMMENT '主键',
    DATA LONGBLOB COMMENT '数据'
) COMMENT '数据';